sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - v4
  - lts/*
  - stable
after_success:
  - npm run semantic-release
env:
  global:
    # npm token
    secure: "Jt3p88aUNe231OZPK0jaM4MOfd+QVZ2dDK2Pb4ZXv8Q9PHk/xcqKsUCgiWOmPTvmGbssoQjWO+I32M5Hmgge/jqVBrMQmmLUrlKoOo2wOOmu4O6obuHNG/go2ws3RvS90iHBL12LOfwU9n+t8j9+Ex292KaTYRefJ1k5g3aREavtfsjVRX/FDXq2+D6Atb0z4d5uiLww4lRaJNBaUWJMflljW8O20Y0nDK1Id+tfnG3E3+0/rQZ5Rms75sf3g0dgxQznnbqTP6cFeyEFIZOHzDhN3WzhhZbhf41ME4yjFs7+jAh0aLhNk6ryZiFcwit7l08+KIg4PjrZlE7EDT35SLM7+UG5QxulqVPy/q0DFSIwJJdhesQdcOQoLgtRImenk5j75mSgXvaqiIC2RwWeth32usBF9p8zFM8eyZXg08UgUS3d92ai0I9MbyTzqlRKWNHDMi/OJSHzSdxEt69V+CXGLhZsC3q80lYYrI44pp38UTufdjkR+1IJrzr3Pgn93eMTGdBJVxCTK1D4kG8fi0CU6DWp/A5Tmv2CNlAjh/FmKHrewAU167oxbgv/Gmtj3QTTpeP+CUa7bCR17LOwomf5xssMUthJMclEegYP8uHNtTqadqOG2GLXVcXhy/eS9PwQS93hJAXqjB3T/X5cuvorcaABCQV3z1MUWhpkAAQ="
    # github token
    secure: "lHeui8wB0IWdSpGiJ6NIONIOIzvIqMWzhcVt3/w93tl9Q5YbeIiBcPFg85u9sLFneeqQ+awyRmrk9lQbXqbd64d/Yva4QOffG3BUikfetovnqY43gzyE65M+CgqyD6SP3NA5YWcXJ0/J/sB9cbkVrcdt70UpfyKG6mUtEQl2q3OaGwcTrHM7cdN0PkCEooFjRJ01KD/WzFoKi+sq85BiIT56UfauLheAsAtQ/6NNIsZeuds5gLKoLeI0uK6wB3fgU8bNSPgK1vykv9P9KnJ4jbWCHWdazQT3e4xtBFxdfBp2kt3HSwOcd0Mdi1S8lF1UBlFEPkFLFSjO2ScRJ6ZDb/rg057DyKsFuQKmRIcmi81jxXWPQPtqeqxrKWWOeEImYGpO1JOKO+eXVQvOLBwKgi60LVHFN3rmEkzbPZ53RFGOxRKKxhP6t7BYofsjDKVYqF8Bo8hR/lG8EEctP/De9DXX9Exbl3YCa7pdjsqmx7IRgLw6J+j115Z8E5Y1/eB+ls6FDlCiof9VQOmNHOXK+OxiYn6by9haQygWG+l6X83AiyIEVZrJxkbZ26CAaUDn04s0V9zg7fRhadwU5OBGEYxhCvrmbkIz4785elgZp+6SmJNRzjCT92FeZjXVhzhcfgyXKAuqnVbCW0RNs31iJkmRVYi115vunqAG0CowQSM="
